# Generated by Django 4.2.16 on 2024-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabchange',
            name='last_warning_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
