# Generated by Django 4.2.16 on 2024-12-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_bank',
        ),
    ]
