# Generated by Django 4.2.16 on 2024-12-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='exam.exam')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionbank')),
                ('selected_questions', models.ManyToManyField(blank=True, related_name='question_banks', to='exam.question')),
            ],
        ),
    ]
