# Generated by Django 4.2.16 on 2024-12-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_questionbankexam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBankExam',
        ),
    ]
